### ISSUE TITLE
Owl

### ISSUE THREAD

**Issue by Nyanter** [ZFAC190/Hootuu-Project#2]
What gender is our owl?

**Comment by ZFAC190** [comment]
Non-binary

**Comment by ZFAC190** [comment]
Maybe Pan

**Comment by ZFAC098** [comment]
![owl](https://user-images.githubusercontent.com/48086679/53558268-8ca34700-3b3f-11e9-8c9d-8131c0fe7f08.png)

**Comment by ZFAC098** [comment]
95x95 px per frame

**Comment by ZFAC098** [comment]
![owl](https://user-images.githubusercontent.com/48086679/53741574-9fdf4b00-3e8e-11e9-8e11-d09fe11c89eb.png)
